### ISSUE TITLE
feat: 소개 섹션 구현

### ISSUE THREAD

**Issue by soma0078** [soma0078/portfolio#3]
## 🌿설명
> 간단한 이력을 담은 `소개` 페이지 작업입니다.

## 🌿To-do
- [x] 소개 섹션 레이아웃 및 디자인 구현
- [x] 툴팁 컴포넌트 구현
- [x] 버튼 컴포넌트 구현
- [x] 경력 및 교육 표시할 아코디언 구현
