### ISSUE TITLE
feat: 프로젝트 섹션 구현

### ISSUE THREAD

**Issue by soma0078** [soma0078/portfolio#5]
## 🌿설명
> 프로젝트를 목록으로 표시하고, 각 프로젝트의 상세 정보를 팝업으로 확인할 수 있도록 하는 **`프로젝트 섹션`** 을 작업합니다.

## 🌿To-do
- [ ] 프로젝트 목록 구현
  - [ ] 각 프로젝트의 제목, 간단한 설명 및 썸네일을 포함한 목록 생성
  - [ ] 프로젝트 목록은 JSON 데이터 로드
  - [ ] 프로젝트 목록을 all, team, single에 따라 필터링 할 수 있는 기능 추가
- [ ] 프로젝트 상세 팝업 구현
  - [ ] 프로젝트 클릭 시 팝업 오픈 기능 추가
  - [ ] 팝업 내에 상세 내용(프로젝트 설명, 기술 스택 등) 표시
  - [ ] 프로젝트 이미지 썸네일 갤러리
  - [ ] 팝업 닫기 버튼 및 배경 클릭 시 닫기 기능 추가
