### ISSUE TITLE
feat: Works 섹션 구현

### ISSUE THREAD

**Issue by soma0078** [soma0078/portfolio#6]
## 🌿설명
> 필요한 기능, 발생한 문제에 대해 적어주세요.

## 🌿To-do
- [ ] 작업물 목록 구현
  - [ ] 여러 개의 작업물 이미지를 가로로 나열하여 스크롤 형태로 구성
- [ ] 작업물 클릭 시 상세 팝업 구현
  - [ ] 팝업 내에 작업물의 상세 내용과 관련 이미지 배치
