### ISSUE TITLE
feat: 컨택트 및 푸터 구현

### ISSUE THREAD

**Issue by soma0078** [soma0078/portfolio#7]
## 🌿설명
> 소셜 미디어 링크 제공하는 **`컨택트 섹션`** 과 웹사이트의 하단 정보를 제공하는 **`푸터`** 를 구현합니다.

## 🌿To-do
- [x] 소셜 미디어 아이콘 및 링크와 간단한 글로 구성된 컨택트 섹션 레이아웃 및 디자인 구현
- [x] 저작권 및 연도 표시한 푸터 구현
- [x] scrollToTop 버튼 구현
